spring:
    application:
        name: EDMIDC-Save-Service
    kafka:
        consumer:
            auto-offset-reset: earliest
            bootstrap-servers: localhost:29092
            group-id: group_iid
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringSerializer




#    spring.influx.url=http://localhost:8086
#    spring.influx.username=<YOUR_USERNAME>
#    spring.influx.password=<YOUR_PASSWORD>
#    spring.influx.database=<YOUR_DATABASE_NAME>