spring:
    application:
        name: EDMIDC-Save-Service
    kafka:
        consumer:
            auto-offset-reset: earliest
            enable-auto-commit: true
            bootstrap-servers: ${KAFKA_BOOTSTRAP_URL:localhost:29092}
            group-id: ${GROUP_ID:group_id}
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringSerializer
        topics: ${KAFKA_TOPICS:edmidc-bitcoin-cdc,error-message-cdc}
    influxdb:
        config:
            url: ${INFLUXDB_URL:http://localhost:8086}
            token: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN:my-super-secret-auth-token}
            org: ${DOCKER_INFLUXDB_INIT_ORG:my-org}
            bucket: ${DOCKER_INFLUXDB_INIT_BUCKET:my-bucket}
management:
    server:
        port: ${SERVER_PORT:8080}

server:
    port: ${SERVER_PORT:8080}
    servlet:
        context-path: /
