on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Build and test
        run: ./mvnw clean package
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          TAG=${GITHUB_REF_NAME}
          docker build -t edmidc-save-service:${TAG} .
          docker tag edmidc-save-service:${TAG} parsazendehdel/edmidc-save-service:${TAG}
          docker push parsazendehdel/edmidc-save-service:${TAG}
